-- Mariana Oliveira e Thiago Abreu

DROP DATABASE IF EXISTS pratica_04;
CREATE DATABASE pratica_04;
USE pratica_04;

CREATE TABLE DEPARTAMENTO (
    COD_DEPART INT PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL,
    DATA_INICIAL DATE
);

CREATE TABLE FUNCIONARIO (
    COD_FUNC INT PRIMARY KEY,           
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(15) UNIQUE NOT NULL,    
    SALARIO DECIMAL(8,2),
    ENDERECO VARCHAR(252),
    SEXO CHAR(1) CHECK (SEXO IN ('M', 'F')),
    COD_SUPER INT,                     
    COD_DEPART INT NOT NULL,             
    CONSTRAINT FK_FUNCIONARIO_SUPERVISOR FOREIGN KEY (COD_SUPER) REFERENCES FUNCIONARIO(COD_FUNC),
    CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO FOREIGN KEY (COD_DEPART) REFERENCES DEPARTAMENTO(COD_DEPART)
);

CREATE TABLE DEPENDENTE (
    COD_FUNC INT,                       
    SEQ INT,                            
    NOME VARCHAR(100) NOT NULL,
    PARENTESCO VARCHAR(30) NOT NULL CHECK (PARENTESCO IN ('PAI', 'MÃE', 'IRMAOS', 'FILHO')),
    DATA_NASC DATE,
    PRIMARY KEY (COD_FUNC, SEQ),
    CONSTRAINT FK_DEPENDENTE_FUNCIONARIO FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC)
);

CREATE TABLE PROJETO (
    COD_PROJ INT PRIMARY KEY,           
    COD_DEPART INT NOT NULL,             
    TITULO VARCHAR(150) NOT NULL,        
    DESCRICAO VARCHAR(252),
    DATA_CAD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PROJETO_DEPARTAMENTO FOREIGN KEY (COD_DEPART) REFERENCES DEPARTAMENTO(COD_DEPART)
);

CREATE TABLE PARTICIPA (
    COD_FUNC INT,                        
    COD_PROJ INT,                      
    HORAS VARCHAR(50),
    PRIMARY KEY (COD_FUNC, COD_PROJ),
    CONSTRAINT FK_PARTICIPA_FUNCIONARIO FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC),
    CONSTRAINT FK_PARTICIPA_PROJETO FOREIGN KEY (COD_PROJ) REFERENCES PROJETO(COD_PROJ)
);

CREATE TABLE LOCALIZACAO (
    COD_DEPART INT,                     
    LOCAL VARCHAR(252),
    PRIMARY KEY (COD_DEPART, LOCAL),
    CONSTRAINT FK_LOCALIZACAO_DEPARTAMENTO FOREIGN KEY (COD_DEPART) REFERENCES DEPARTAMENTO(COD_DEPART)
);

-- Exercício 1
ALTER TABLE PROJETO ADD (
    STATUS TINYINT NOT NULL,
    CONSTRAINT CK_PROJETO_STATUS CHECK (STATUS IN (0, 1))
);
ALTER TABLE PROJETO MODIFY TITULO VARCHAR(155); 
ALTER TABLE PROJETO RENAME COLUMN DATA_CAD TO DATA_CADASTRO;

-- Exercício 2
CREATE TABLE ENDERECO (
    COD_ENDERECO INT PRIMARY KEY,       
    LOGRADOURO VARCHAR(100) NOT NULL,  
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CEP VARCHAR(10)
);

CREATE TABLE FUNCIONARIO_ENDERECO (
    COD_FUNC INT NOT NULL,              
    COD_ENDERECO INT NOT NULL,          
    TIPO_ENDERECO VARCHAR(20),
    PRIMARY KEY (COD_FUNC, COD_ENDERECO),
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC),
    FOREIGN KEY (COD_ENDERECO) REFERENCES ENDERECO(COD_ENDERECO)
);

ALTER TABLE FUNCIONARIO DROP COLUMN ENDERECO;

-- Exercício 3
CREATE TABLE PARENTESCO (
    COD_PARENTESCO INT PRIMARY KEY,    
    DESCRICAO VARCHAR(30) NOT NULL
);

INSERT INTO PARENTESCO VALUES (1, 'PAI');
INSERT INTO PARENTESCO VALUES (2, 'MÃE');
INSERT INTO PARENTESCO VALUES (3, 'IRMAOS');
INSERT INTO PARENTESCO VALUES (4, 'FILHO');

ALTER TABLE DEPENDENTE DROP COLUMN PARENTESCO;
ALTER TABLE DEPENDENTE ADD COD_PARENTESCO INT NOT NULL;
ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_PARENTESCO 
    FOREIGN KEY (COD_PARENTESCO) REFERENCES PARENTESCO(COD_PARENTESCO);
ALTER TABLE DEPENDENTE ADD (CPF VARCHAR(15), CONSTRAINT UK_DEPENDENTE_CPF UNIQUE (CPF));

ALTER TABLE DEPENDENTE DROP FOREIGN KEY FK_DEPENDENTE_FUNCIONARIO;
ALTER TABLE DEPENDENTE 
ADD CONSTRAINT FK_DEPENDENTE_FUNCIONARIO 
FOREIGN KEY (COD_FUNC) 
REFERENCES FUNCIONARIO(COD_FUNC)
ON DELETE CASCADE;

-- Exercício 4
ALTER TABLE PARTICIPA RENAME TO FUNC_PROJETO;